% Abstraction from entering the entire function into Python

function OS = proc_oscfar(train, guard, rank, Pfa)
    OS = phased.CFARDetector('NumTrainingCells',double(train), ...
        'NumGuardCells',double(guard), ...
        'ThresholdFactor', 'Auto', ...
        'ProbabilityFalseAlarm', double(Pfa), ...
        'Method', 'OS', ...
        'ThresholdOutputPort', true, ...
        'Rank',double(rank));
end